### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by JoDeveloper** [rodrigobastosv/loading_overlay#2]
```

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3781
#1      Element._debugCheckStateIsActiveForAncestorLookup 
package:flutter/…/widgets/framework.dart:3795
#2      Element.findAncestorWidgetOfExactType 
package:flutter/…/widgets/framework.dart:3887
#3      OverlayControllerWidget.of 
package:loader_overlay/src/overlay_controller_widget.dart:9
#4      OverlayControllerWidgetExtension.getOverlayController 
package:loader_overlay/src/overlay_controller_widget_extension.dart:7
...
════════════════════════════════════════════════════════════════════════════════
```

**Comment by rodrigobastosv** [comment]
Hi @JoDeveloper , can you describe the steps to reproduce this error?

**Comment by kauemurakami** [comment]
Estou com o mesmo problema hoje. creio que seja algo a ver com o "custom", estou tentando adicionar uma imagem em um container, vou expor um pouco de código aqui.
**stack**
```
The following assertion was thrown while finalizing the widget tree:
I/flutter (25412): Looking up a deactivated widget's ancestor is unsafe.
I/flutter (25412): At this point the state of the widget's element tree is no longer stable.
I/flutter (25412): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
I/flutter (25412): calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
I/flutter (25412): When the exception was thrown, this was the stack:
I/flutter (25412): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3825:9)
I/flutter (25412): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3839:6)
I/flutter (25412): #2      Element.findAncestorWidgetOfExactType (package:flutter/src/widgets/framework.dart:3931:12)
I/flutter (25412): #3      OverlayControllerWidget.of (package:loader_overlay/src/overlay_controller_widget.dart:10:15)
I/flutter (25412): #4      OverlayControllerWidgetExtension.getOverlayController (package:loader_overlay/src/overlay_controller_widget_extension.dart:8:31)
```

**main.dart**
```
GlobalLoaderOverlay(
      overlayColor: mainColor,
      overlayOpacity: 0.5,
      useDefaultLoading: false,
          child: GetMaterialApp(
        initialRoute: Routes.LANDING,
        initialBinding: LandingBinding(),
        home: LandingPage(),
        getPages: AppPages.pages,
        theme: appThemeData,
      ),
    )
```
**CadastroPage.dart** 
Aqui irei exibir o Loading, o fundo aparece com a cor customizada por mim no main, meu método cadastro funciona perfeitamente. Após esse mostratei meu widgetCustom
```
class CadastroPage extends GetView<CadastroController> {
  static final GlobalKey formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return LoaderOverlay(
      overlayWidget: CustomLoading(message: 'Salvando informações, é rapidinho !'),
          useDefaultLoading: false,
          child: Scaffold(
            body: SafeArea(...
...
...
  CustomButtonWidget( 
                                    text: 'Registrar',
                                    callback: () async {
                                      final FormState form = formKey.currentState;
                                      if (form.validate()) {
                                        context.showLoaderOverlay();
                                        form.save();
                                        await controller.cadastrar();
                                        context.hideLoaderOverlay();
                                        Get.offAllNamed(Routes.HOME, arguments: controller.user);
                                      }
                                    },
                                  )
```

**CustomLoadingWidget**
```
import 'package:flutter/material.dart';

class CustomLoading extends Container {
  final String message;
  final Color color;
  CustomLoading({@required this.message, this.color = Colors.white});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 300,
      width: 350,
      decoration: BoxDecoration(
        image:
            DecorationImage(image: AssetImage('assets/images/save_data.png'),fit: BoxFit.cover),
      ),
      child: CircularProgressIndicator(semanticsLabel: 'Estamos salvando seus dados, é rapidinho.',),
    );
  }
}

```

O package possui limitações quanto a filhos internos, ou imagens ? Espero ter ajudado, muitas pessoas devem estar passando pelo mesmo problema ao tentar isso.

**Comment by kauemurakami** [comment]
If it is still useful, you should be sure to use hideLoaderOverlay () after your async function is finished.
I decided that way

 ```
CustomButtonWidget(
                                    text: 'Registrar',
                                    callback: () async {  
                                      final FormState form =
                                          formKey.currentState;
                                      if (form.validate()) {
                                        context.showLoaderOverlay();
                                        form.save();
                                        controller.cadastrar().then((value) =>
                                            context
                                                .hideLoaderOverlay());
                                        Get.offAllNamed(Routes.HOME,
                                            arguments: controller.user);
                                      }
                                    },
                                  )
```

**Comment by rodrigobastosv** [comment]
The bug is fixed on the 1.1.1 version!
